# Generated by Django 3.0.4 on 2020-03-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_object',
            name='service_category',
        ),
    ]
