# Generated by Django 3.0.3 on 2020-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0004_auto_20200311_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ставка'),
        ),
    ]
