# Generated by Django 3.0.3 on 2020-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0005_auto_20200311_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='friday',
            field=models.BooleanField(default=True, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='driver',
            name='monday',
            field=models.BooleanField(default=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='driver',
            name='saturday',
            field=models.BooleanField(default=True, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='driver',
            name='sunday',
            field=models.BooleanField(default=True, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='driver',
            name='thursday',
            field=models.BooleanField(default=True, verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tuesday',
            field=models.BooleanField(default=True, verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='driver',
            name='wednesday',
            field=models.BooleanField(default=True, verbose_name='Среда'),
        ),
    ]
