# Generated by Django 3.0.4 on 2020-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0008_auto_20200317_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
