# Generated by Django 3.0.4 on 2020-03-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0009_driver_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('slug', models.SlugField(blank=True, max_length=15, verbose_name='Url')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Наличные')),
                ('cash_card', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Карта')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxiapp.Working_day')),
            ],
            options={
                'verbose_name': 'Движение по кассе',
                'verbose_name_plural': 'Движения по кассе',
            },
        ),
    ]
