# Generated by Django 3.0.4 on 2020-03-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0011_cashboxdbt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashboxDbt',
        ),
    ]
