# Generated by Django 3.0.4 on 2020-03-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0013_auto_20200327_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='working_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxiapp.Working_day'),
        ),
    ]
