# Generated by Django 3.0.4 on 2020-04-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxiapp', '0015_remove_cashbox_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorking_day',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рабочего дня')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ставка')),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ГСМ')),
                ('penalties', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Штрафы')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Наличные')),
                ('cash_card', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Карта')),
                ('cashless', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Безналичные')),
                ('debt_of_day', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Долг дня')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taxiapp.Driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Рабочий день',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('driver_license', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер В/У')),
                ('car_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер А/М')),
                ('car_model', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Марка А/М')),
                ('fuel_card', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Топливная карта')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ставка')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Долг')),
                ('monday', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=True, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=True, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=True, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=True, verbose_name='Воскресенье')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Водитель',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashbox',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('slug', models.SlugField(blank=True, max_length=15, verbose_name='Url')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Наличные')),
                ('cash_card', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Карта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('working_day', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taxiapp.Working_day')),
            ],
            options={
                'verbose_name': 'historical Движение по кассе',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
