# Generated by Django 3.0.4 on 2020-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0016_historicalcashbox_historicaldriver_historicalworking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='date',
            field=models.DateTimeField(verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='historicalcashbox',
            name='date',
            field=models.DateTimeField(verbose_name='Дата операции'),
        ),
    ]
