# Generated by Django 3.0.4 on 2020-05-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0017_auto_20200513_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('car_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер')),
                ('car_brand', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Марка')),
                ('car_model', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='taxiapp.Car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='car',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taxiapp.Car', verbose_name='Автомобиль'),
        ),
    ]
