# Generated by Django 3.0.4 on 2020-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0018_auto_20200513_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='driver',
            name='fuel_card_2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Топливная карта 2'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='fuel_card_2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Топливная карта 2'),
        ),
    ]
