# Generated by Django 3.0.4 on 2020-03-26 12:44

import certapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('object_top', models.BooleanField(default=False, verbose_name='Поднять в топ')),
                ('object_slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('object_image', models.ImageField(blank=True, default=None, null=True, upload_to=certapp.models.get_image_name, verbose_name='Изображение')),
                ('build_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certapp.Cert_object', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
