# Generated by Django 3.0.4 on 2020-03-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='build_object',
            new_name='cert_object',
        ),
    ]
