# Generated by Django 3.0.4 on 2020-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_auto_20200317_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_object',
            name='rent_category',
            field=models.CharField(choices=[('equipment', 'Техника'), ('tool', 'Инструмент')], default='equipment', max_length=10, verbose_name='Категория'),
        ),
    ]
