# Generated by Django 3.0.3 on 2020-03-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_auto_20200318_1759'),
        ('rentapp', '0003_auto_20200312_1718'),
    ]

    operations = [
    ]
