# Generated by Django 3.0.3 on 2020-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_merge_20200319_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_object',
            name='rent_category',
            field=models.CharField(choices=[('equipment', 'Техника'), ('tool', 'Инструмент')], default='equipment', max_length=10, verbose_name='Категория'),
        ),
    ]
