# Generated by Django 3.0.4 on 2020-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('car_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер')),
                ('car_brand', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Марка')),
                ('car_model', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
