# Generated by Django 2.2.5 on 2020-02-10 10:59

from django.db import migrations, models
import django.db.models.deletion
import objectapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_date', models.DateField(auto_now_add=True, verbose_name='Дата рабочего дня')),
                ('object_title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('object_desc', models.TextField(blank=True, max_length=1024, verbose_name='Описание')),
                ('object_top', models.BooleanField(default=False, verbose_name='Поднять в топ')),
                ('object_slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('object_image', models.ImageField(blank=True, default=None, null=True, upload_to=objectapp.models.get_image_name, verbose_name='Изображение')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('build_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectapp.Build_object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
