# Generated by Django 2.2.5 on 2020-02-19 14:01

from django.db import migrations, models
import objectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('objectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='object_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=objectapp.models.get_image_name, verbose_name='Изображение 1170х780'),
        ),
    ]
